#!/usr/bin/env python3

def is_valid_IPv4_octet(octet):
    """Returns True if octet represents a valid IPv4 octet, False otherwise"""
    try:
        if 0 <= int(octet) <= 255:
            return True
        else:
            return False
    except ValueError:
        return False

def is_valid_IPv4(ip):
    """Returns True if ip represents a valid IPv4 address, False otherwise"""
    octet_list = ip.split(".")
    
    if len(octet_list) != 4:
        return False

    for octet in octet_list:
        if not is_valid_IPv4_octet(octet):
            return False
    return True

def is_valid_IPv6_hextet(hextet):
    """Returns True if hextet represents a valid IPv6 hextet, False otherwise"""
    try:
        if 0 <= int(hextet,16) <= 65535:
            return True
        else:
            return False
    except ValueError:
        return False

def is_valid_IPv6(ip):
    """Returns True if ip represents a valid IPv6 address, False otherwise"""
    
    hextet_list = ip.split(":")
    
    if len(hextet_list) != 8:
        return False
    
    for hextet in hextet_list:
        if not is_valid_IPv6_hextet(hextet):
            return False
    
    return True

def is_valid_IP(ip):
    """Returns True if ip represents a valid IPv4 or IPv6 address False otherwise"""
    if is_valid_IPv4(ip) or is_valid_IPv6(ip):
        return True
    else:
        return False

# You should look at task/test.py and extend the test suite we provided!

