#!/usr/bin/env python3


# This signature is required for the automated grading to work.
# Do not rename the function or change its list of parameters!
def min_domino_rotations(top, bottom):
    rotations = 0
    storage_var = 0
    try:
        merge_list = list(zip(top, bottom))
        top_list = [((i, "top") if i in top else "bottom") for i in top if all(i in j for j in merge_list)]
        bottom_list = [(("bottom", i) if i in bottom else "top") for i in bottom if all(i in j for j in merge_list)]
        domino = int(top_list[0][0])
    except:
        return -1

    if len(top_list) > len(bottom_list):
        for i, j in merge_list:
            if i == domino:
                continue
            else:
                rotations += 1
        return rotations
    elif len(top_list) < len(bottom_list):
        for i, j in merge_list:
            if j == domino:
                continue
            else:
                rotations += 1
        return rotations
    else:
        return -1


# The following line calls the function which will print # value to the Console.
# This way you can check what it does.
# However, we encourage you to write tests, because then you
# can easily test many different values on every "Test & Run"!

print(min_domino_rotations([2, 6, 2, 1, 2, 2], [5, 2, 4, 2, 3, 2]))
print(min_domino_rotations([3, 5, 1, 2, 6], [3, 6, 3, 3, 6]))
